/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AppRouteImport } from './routes/app'
import { Route as ComingSoonRouteImport } from './routes/coming-soon'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MerchantRouteImport } from './routes/merchant'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PayRouteImport } from './routes/pay'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ApiHealthRouteImport } from './routes/api.health'
import { Route as ApiInterpretPaymentRouteImport } from './routes/api.interpret-payment'
import { Route as MerchantIndexRouteImport } from './routes/merchant.index'
import { Route as MerchantApplyRouteImport } from './routes/merchant.apply'
import { Route as ReceiptReceiptIdRouteImport } from './routes/receipt.$receiptId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ComingSoonRoute = ComingSoonRouteImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantRoute = MerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PayRoute = PayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInterpretPaymentRoute = ApiInterpretPaymentRouteImport.update({
  id: '/api/interpret-payment',
  path: '/api/interpret-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantIndexRoute = MerchantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MerchantRoute,
} as any)
const MerchantApplyRoute = MerchantApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => MerchantRoute,
} as any)
const ReceiptReceiptIdRoute = ReceiptReceiptIdRouteImport.update({
  id: '/receipt/$receiptId',
  path: '/receipt/$receiptId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/app': typeof AppRoute
  '/coming-soon': typeof ComingSoonRoute
  '/login': typeof LoginRoute
  '/merchant': typeof MerchantRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/pay': typeof PayRoute
  '/profile': typeof ProfileRoute
  '/api/health': typeof ApiHealthRoute
  '/api/interpret-payment': typeof ApiInterpretPaymentRoute
  '/merchant/apply': typeof MerchantApplyRoute
  '/receipt/$receiptId': typeof ReceiptReceiptIdRoute
  '/merchant/': typeof MerchantIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/app': typeof AppRoute
  '/coming-soon': typeof ComingSoonRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/pay': typeof PayRoute
  '/profile': typeof ProfileRoute
  '/api/health': typeof ApiHealthRoute
  '/api/interpret-payment': typeof ApiInterpretPaymentRoute
  '/merchant/apply': typeof MerchantApplyRoute
  '/receipt/$receiptId': typeof ReceiptReceiptIdRoute
  '/merchant': typeof MerchantIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/app': typeof AppRoute
  '/coming-soon': typeof ComingSoonRoute
  '/login': typeof LoginRoute
  '/merchant': typeof MerchantRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/pay': typeof PayRoute
  '/profile': typeof ProfileRoute
  '/api/health': typeof ApiHealthRoute
  '/api/interpret-payment': typeof ApiInterpretPaymentRoute
  '/merchant/apply': typeof MerchantApplyRoute
  '/receipt/$receiptId': typeof ReceiptReceiptIdRoute
  '/merchant/': typeof MerchantIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/app'
    | '/coming-soon'
    | '/login'
    | '/merchant'
    | '/notifications'
    | '/pay'
    | '/profile'
    | '/api/health'
    | '/api/interpret-payment'
    | '/merchant/apply'
    | '/receipt/$receiptId'
    | '/merchant/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/app'
    | '/coming-soon'
    | '/login'
    | '/notifications'
    | '/pay'
    | '/profile'
    | '/api/health'
    | '/api/interpret-payment'
    | '/merchant/apply'
    | '/receipt/$receiptId'
    | '/merchant'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/app'
    | '/coming-soon'
    | '/login'
    | '/merchant'
    | '/notifications'
    | '/pay'
    | '/profile'
    | '/api/health'
    | '/api/interpret-payment'
    | '/merchant/apply'
    | '/receipt/$receiptId'
    | '/merchant/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AppRoute: typeof AppRoute
  ComingSoonRoute: typeof ComingSoonRoute
  LoginRoute: typeof LoginRoute
  MerchantRoute: typeof MerchantRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  PayRoute: typeof PayRoute
  ProfileRoute: typeof ProfileRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiInterpretPaymentRoute: typeof ApiInterpretPaymentRoute
  ReceiptReceiptIdRoute: typeof ReceiptReceiptIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coming-soon': {
      id: '/coming-soon'
      path: '/coming-soon'
      fullPath: '/coming-soon'
      preLoaderRoute: typeof ComingSoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant': {
      id: '/merchant'
      path: '/merchant'
      fullPath: '/merchant'
      preLoaderRoute: typeof MerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay': {
      id: '/pay'
      path: '/pay'
      fullPath: '/pay'
      preLoaderRoute: typeof PayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/interpret-payment': {
      id: '/api/interpret-payment'
      path: '/api/interpret-payment'
      fullPath: '/api/interpret-payment'
      preLoaderRoute: typeof ApiInterpretPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant/': {
      id: '/merchant/'
      path: '/'
      fullPath: '/merchant/'
      preLoaderRoute: typeof MerchantIndexRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/merchant/apply': {
      id: '/merchant/apply'
      path: '/apply'
      fullPath: '/merchant/apply'
      preLoaderRoute: typeof MerchantApplyRouteImport
      parentRoute: typeof MerchantRoute
    }
    '/receipt/$receiptId': {
      id: '/receipt/$receiptId'
      path: '/receipt/$receiptId'
      fullPath: '/receipt/$receiptId'
      preLoaderRoute: typeof ReceiptReceiptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MerchantRouteChildren {
  MerchantApplyRoute: typeof MerchantApplyRoute
  MerchantIndexRoute: typeof MerchantIndexRoute
}

const MerchantRouteChildren: MerchantRouteChildren = {
  MerchantApplyRoute: MerchantApplyRoute,
  MerchantIndexRoute: MerchantIndexRoute,
}

const MerchantRouteWithChildren = MerchantRoute._addFileChildren(
  MerchantRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AppRoute: AppRoute,
  ComingSoonRoute: ComingSoonRoute,
  LoginRoute: LoginRoute,
  MerchantRoute: MerchantRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  PayRoute: PayRoute,
  ProfileRoute: ProfileRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiInterpretPaymentRoute: ApiInterpretPaymentRoute,
  ReceiptReceiptIdRoute: ReceiptReceiptIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
